import Origami.Huzita.Axioms
/- aled -/

/- do the construction starting from (0, 0) and
prove that the angle is trisected -/
-- we'll work in ℝ²
-- O = (0,0), A = (0, 1), B = (0, 2).
/- the goal is to prove that the construction generated by
trisection_fold_exists actually trisects the angle -/
