import Origami.lightweight_definitions.Huzita_axioms

open Origami
open scoped Classical

-- Geometric entities selected in the web interface -- unmodified output of
-- origami-sim's conversion script (OrigamiAPI.generate_lean_code), kept
-- exactly as generated so what follows is reasoning *about* that output,
-- not a rewrite of it.
axiom p1 : Point -- picked at (1, 0)
axiom p2 : Point -- picked at (0.5, 1)
axiom l1 : Line -- crease (0, 0.125) -> (1, 0.625)
axiom p3 : Point -- picked at (1, 0.625)
axiom p4 : Point -- picked at (0, 0.125)
axiom p5 : Point -- picked at (0.5, 0.375)

-- Side conditions the stacked axioms need, that aren't derivable from the
-- opaque Point/Line axioms above -- postulated the same way the picked
-- geometry itself is postulated.
axiom hyp1 : p1 ≠ p2

-- Sequence of 1 stacked Huzita axiom(s) generated by origami-sim
theorem haga_construction : True := by
  obtain ⟨f1, h1, -⟩ := huzita_2 p1 p2 hyp1
  trivial

-- `huzita_2` needs `p1 ≠ p2`: a fold fixes `p` exactly when `p` lies on the crease, so if
-- `p1 = p2` then every crease through `p1` places `p1` onto `p2` and uniqueness fails.
lemma huzita_2_uniqueness (f1 f2 : Fold) (p1 p2 : Point) (hne : p1 ≠ p2) :
  f_places_p f1 p1 = p2 ∧ f_places_p f2 p1 = p2 → f1 = f2 := by
    intro h
    have hu : ∃! f : Fold, f_places_p f p1 = p2 := huzita_2 p1 p2 hne
    have h1 : f_places_p f1 p1 = p2 := by simp [h.left]
    have h2 : f_places_p f2 p1 = p2 := by simp [h.right]
    have heq : f1 = f2 := hu.unique h1 h2
    exact heq;

def is_huzita_2_compliant_fold (f : Fold) (p1 p2 : Point) : Prop :=
  f_places_p f p1 = p2

-- ---------------------------------------------------------------------
-- Everything above this line is origami-sim's construction, untouched.
-- Everything below reasons *about* it, without altering it: p1/p2 stay
-- the same opaque axioms the UI produced -- we separately postulate what
-- their "picked at" comments already say (exactly as legitimate a leap as
-- postulating the points' existence in the first place), which is enough
-- to actually use the construction rather than just type-check it.
-- ---------------------------------------------------------------------

axiom p1_coords : p1 = (⟨1, 0⟩ : Point)
axiom p2_coords : p2 = (⟨(1/2 : ℚ), 1⟩ : Point)

-- Re-derives the same fold `haga_construction` proves exists, except this
-- time the witness is kept instead of thrown away by `trivial` -- so it can
-- actually be handed to `haga_first_theorem` below.
theorem haga_fold_exists : ∃ f : Fold, is_huzita_2_compliant_fold f p1 p2 := by
  obtain ⟨f1, h1, -⟩ := huzita_2 p1 p2 hyp1
  exact ⟨f1, h1⟩

theorem haga_first_theorem (crease : Fold) :
  let pA : Point := ⟨1, 0⟩
  let pB : Point := ⟨(1/2 : ℚ), 1⟩
  let _ : Point := ⟨0, 0⟩
  let pLeftIntersect : Point := ⟨0, (1/3 : ℚ)⟩
  is_huzita_2_compliant_fold crease pA pB →
  let lowerEdge : Line := {a := 0, b := 1, c := 0, nontrivial := by simp, normalized := by simp}
  on_line (f_places_l crease lowerEdge) pLeftIntersect:= by
    intro pA pB pC pLeftIntersect h lowerEdge
    let alsoCrease : Fold := {a := 1, b := -2, c := 1/4, nontrivial:=by simp, normalized:=by simp}
    let alsopB : Point := f_places_p alsoCrease pA
    have pBEquiv : (alsopB = pB) := by
      unfold alsopB f_places_p alsoCrease pA pB
      simp [is_huzita_2_compliant_fold, pA, pB] at *
      grind
    have creaseEquiv : alsoCrease = crease := by

      have h_combined : f_places_p alsoCrease pA = f_places_p crease pA := by
        rw [←pBEquiv] at h
        grind[is_huzita_2_compliant_fold]

      have hne : pA ≠ pB := by
        intro hEq
        have hy := congrArg Point.y hEq
        unfold pA pB at hy
        norm_num at hy

      apply huzita_2_uniqueness alsoCrease crease pA pB hne
      trivial

    have alsoOn : on_line (f_places_l alsoCrease lowerEdge) pLeftIntersect := by
      unfold on_line f_places_l alsoCrease lowerEdge pLeftIntersect
      simp; norm_num;

    rw[← creaseEquiv]
    convert alsoOn

-- The concrete payoff: the fold origami-sim actually constructed (folding
-- the picked corner p1 onto the picked point p2) provably crosses the lower
-- edge at (0, 1/3) -- no arbitrary `crease` parameter, no unproven "assume
-- such a fold exists": `haga_fold_exists` supplies the witness (built from
-- the untouched construction above), `haga_first_theorem` supplies the
-- property once we substitute in what the UI told us p1/p2 actually are.
theorem haga_result :
  let pLeftIntersect : Point := ⟨0, (1/3 : ℚ)⟩
  let lowerEdge : Line := {a := 0, b := 1, c := 0, nontrivial := by simp, normalized := by simp}
  on_line (f_places_l (Classical.choose haga_fold_exists) lowerEdge) pLeftIntersect := by
    intro pLeftIntersect lowerEdge
    -- `Classical.choose haga_fold_exists`'s well-typedness is itself tied to
    -- `p1`/`p2` (via haga_fold_exists's statement), so rewriting p1/p2
    -- inside a hypothesis that still mentions it directly hits Lean's
    -- "motive is not type correct" -- naming it first as a plain local
    -- decouples the two.
    set crease := Classical.choose haga_fold_exists with hcrease
    have h : is_huzita_2_compliant_fold crease p1 p2 := Classical.choose_spec haga_fold_exists
    rw [p1_coords, p2_coords] at h
    exact haga_first_theorem crease h

theorem haga_gen_equation ( n : ℚ ) (crease : Fold) :
  let pA : Point := ⟨1, 0⟩
  let pB : Point := ⟨n, 1⟩
  let pLeftIntersect : Point := ⟨0, (n / ( 2 - n ))⟩
  ( n > 0 ) ∧ ( n < 1 ) ∧ (is_huzita_2_compliant_fold crease pA pB) →
  let lowerEdge : Line := {a := 0, b := 1, c := 0, nontrivial := by simp, normalized := by simp}
  on_line (f_places_l crease lowerEdge) pLeftIntersect:= by
    intro pA pB pLeftIntersect h lowerEdge
    have h_denom : n - 1 ≠ 0 := by linarith
    have h_denom_cast : ↑n - 1 ≠ 0 := by exact_mod_cast h_denom
    have h_denom2 : 2 - n ≠ 0 := by linarith
    have h_denom2_cast : 2 - ↑n ≠ 0 := by exact_mod_cast h_denom2
    let alsoCrease : Fold := {
      a := 1,
      b := 1 / (n - 1),
      c := - (n^2 / (2 * (n - 1))),
      nontrivial := by simp,
      normalized := by grind
    }
    let alsopB : Point := f_places_p alsoCrease pA
    have pBEquiv : (alsopB = pB) := by
      unfold alsopB f_places_p alsoCrease pA pB
      simp [is_huzita_2_compliant_fold, pA, pB] at *
      field_simp
      have h_pBEquiv1 : 1 + 1 / (n - 1) ^ 2 - (2 + -(n ^ 2 / (n - 1))) = n * (1 + 1 / (n - 1) ^ 2) := by
        field_simp [h_denom]
        ring
      have h_pBEquiv2 : -((2 + -(n ^ 2 / (n - 1))) / (n - 1)) = 1 + 1 / (n - 1) ^ 2 := by
        field_simp [h_denom]
        ring
      constructor
      · exact_mod_cast h_pBEquiv1
      · exact_mod_cast h_pBEquiv2

    have creaseEquiv : alsoCrease = crease := by
      have h_combined : f_places_p alsoCrease pA = f_places_p crease pA := by
        rw [←pBEquiv] at h
        grind[is_huzita_2_compliant_fold]

      have hne : pA ≠ pB := by
        intro hEq
        have hy := congrArg Point.y hEq
        unfold pA pB at hy
        norm_num at hy

      apply huzita_2_uniqueness alsoCrease crease pA pB hne
      grind

    have alsoOn : on_line (f_places_l alsoCrease lowerEdge) pLeftIntersect := by
      unfold on_line f_places_l alsoCrease lowerEdge pLeftIntersect
      simp
      field_simp [h_denom_cast]
      split_ifs with h_if
      · exfalso
        apply h_denom
        exact_mod_cast h_if
      · field_simp
        simp
        right
        norm_cast
        field_simp [h_denom2_cast]
        ring

    rw[← creaseEquiv]
    convert alsoOn
